"""fix_model_relationships

Revision ID: e8446d6c044a
Revises: f3be6d9e944d
Create Date: 2022-03-10 20:45:03.881323

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e8446d6c044a"
down_revision = "f3be6d9e944d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review", sa.Column("rating", sa.Float(), nullable=True))
    op.add_column("review", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "review", "user", ["user_id"], ["id"])
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "review", type_="foreignkey")
    op.drop_column("review", "user_id")
    op.drop_column("review", "rating")
    # ### end Alembic commands ###
