"""create_base

Revision ID: f3be6d9e944d
Revises: 
Create Date: 2022-03-09 19:39:43.416282

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "f3be6d9e944d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("point", "country", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "point",
        "latitude",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "point",
        "longitude",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.add_column("user", sa.Column("name", sa.String(), nullable=True))
    op.drop_index("ix_user_full_name", table_name="user")
    op.create_index(op.f("ix_user_created_at"), "user", ["created_at"], unique=False)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("full_name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.create_index("ix_user_full_name", "user", ["full_name"], unique=False)
    op.drop_column("user", "name")
    op.alter_column(
        "point",
        "longitude",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "point",
        "latitude",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("point", "country", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###
